# Generated by Django 2.1.5 on 2021-12-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20211228_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_choices',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='app1.category'),
        ),
    ]
