# Generated by Django 2.1.5 on 2022-01-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_category_category_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_choices',
        ),
    ]
